title: Richard Hoppe
logo: /assets/img/RichardHoppePhoto_new.jpg
description: >
  Astronomy PhD student at the Max-Planck-Institut for Astronomy, Heidelberg.
  I am part of the stellar spectroscopy group led by Maria Bergemann.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
