title: Richard Hoppe
logo: /assets/img/RichardHoppePhoto_new.jpg
description: |
  PhD student in Astronomy<br>
  Stellar Spectroscopy Group<br>
  Supervisor: Maria Bergemann<br>
  Max-Planck-Institut for Astronomy, Heidelberg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
