title: Richard Hoppe
logo: /assets/img/RichardHoppePhoto_new.jpg
description: Astronomy PhD student at the MPIA, Heidelberg.
  position: PhD Student
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
