title: Richard Hoppe
logo: /assets/img/RichardHoppePhoto_new.jpg
description: |
  PhD student in Astronomy\n
  Stellar Spectroscopy Group\n
  Supervisor: Maria Bergemann\n
  Max-Planck-Institut for Astronomy, Heidelberg\n
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
